# included templates
include:
  # Docker template
  - project: "to-be-continuous/docker"
    ref: "5.8"
    file: "templates/gitlab-ci-docker.yml"
  # Node.js template
  - project: "to-be-continuous/node"
    ref: "3.12"
    file: "templates/gitlab-ci-node.yml"


# your pipeline stages
stages:
  - build
  - test
  - package-build
  - package-test
  - infra
  - deploy
  - acceptance
  - publish
  - infra-prod
  - production